/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "surface": "#fbf9f5",
              "on-secondary-container": "#245a50",
              "secondary-container": "#b6eee0",
              "tertiary-dim": "#883c2e",
              "on-surface-variant": "#5e605b",
              "on-surface": "#31332f",
              "error-container": "#fa746f",
              "primary-fixed-dim": "#87d0f0",
              "primary-container": "#95deff",
              "surface-container-highest": "#e3e3dc",
              "on-error-container": "#6e0a12",
              "on-secondary-fixed": "#0c483e",
              "surface-variant": "#e3e3dc",
              "tertiary-container": "#fd9886",
              "surface-bright": "#fbf9f5",
              "surface-tint": "#056783",
              "surface-dim": "#dadad4",
              "surface-container-high": "#e9e8e3",
              "surface-container": "#efeee8",
              "error": "#a83836",
              "inverse-on-surface": "#9e9d99",
              "surface-container-lowest": "#ffffff",
              "outline": "#7a7b76",
              "primary": "#056783",
              "secondary-fixed-dim": "#a8dfd2",
              "inverse-primary": "#95deff",
              "secondary-fixed": "#b6eee0",
              "secondary-dim": "#265c51",
              "on-error": "#fff7f6",
              "on-secondary": "#e3fff6",
              "primary-fixed": "#95deff",
              "inverse-surface": "#0e0e0c",
              "on-primary": "#f2faff",
              "primary-dim": "#005a74",
              "on-tertiary-fixed-variant": "#6a2519",
              "on-primary-container": "#005066",
              "on-tertiary-container": "#5e1c12",
              "on-tertiary-fixed": "#3d0401",
              "on-tertiary": "#fff7f6",
              "on-primary-fixed": "#003b4d",
              "tertiary-fixed-dim": "#ed8b7a",
              "surface-container-low": "#f5f4ef",
              "secondary": "#33685d",
              "on-secondary-fixed-variant": "#2f645a",
              "background": "#fbf9f5",
              "outline-variant": "#b2b2ac",
              "error-dim": "#67040d",
              "tertiary-fixed": "#fd9886",
              "tertiary": "#974739",
              "on-primary-fixed-variant": "#005a73",
              "on-background": "#31332f"
          },
          "fontFamily": {
              "headline": ["Manrope", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
          }
      },
  },
  plugins: [],
}
